version: '3'
services:
    web:
        depends_on: 
            - zookeeper
            - redis
        build: .
        ports:
            - "8080:8080"
        networks: 
            - web-go
    redis:
        image: redis:alpine
        container_name: redis
        ports: ["6379"]
        networks:
            - web-go
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always
        hostname: zoo1
        volumes:
            - ./zoo/data:/var/lib/zookeeper/data
        ports:
            - 2181:2181
        networks: 
            - web-go   
networks: 
    web-go: